### ISSUE TITLE
"This site can’t be reached" ❌

### ISSUE THREAD

**Issue by alnahian2003** [petrovicstefanrs/vr_library_interface#8]
[Live link](http://www.vrbookreader.io) not working perfectly.
Seems like there might be some problem with either the domain renewal or the hosting.
![issue](https://user-images.githubusercontent.com/61485238/152778283-876a534b-4882-4014-bc47-900dc823d6b6.png)

Please take care of the issue asap 👐

**Comment by petrovicstefanrs** [comment]
@alnahian2003 I haven't worked on this project for a few years now, and have no intention of continuing work on it. You could still probably make it work locally for yourself if you wanted to try, but I won't be hosting it online again, that domain has expired a long time ago.
